# Generated by Django 3.2 on 2021-12-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_entry_wcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='wcount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
