# Generated by Django 3.2 on 2021-12-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sentiment',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
    ]
